version: "3.5"

networks:
  sonic_pi:
    external: true
    name: sonic_pi

services:
  client:
    networks:
    - sonic_pi
    build: .
    environment:
    - PYTHONUNBUFFERED=1
    - SERVER=192.168.0.100
    env_file:
    - .env
    ports:
    - 6667:6667

