version: "3.5"

networks:
  sonic_pi:
    external: true
    name: sonic_pi

services:
  server:
    networks:
    - sonic_pi
    build: .
    environment:
    - PYTHONUNBUFFERED=1
    ports:
    - 42069:42069

