version: "3.5"

networks:
  sonic_pi:
    external: true
    name: sonic_pi

services:
  ui:
    networks:
    - sonic_pi
    build: .
    tty: true
    stdin_open: true

    environment:
    - PYTHONUNBUFFERED=1
    - TERM=xterm

    ports:
    - 6969:6969

